os: linux
dist: bionic
language: python
python:
  # not actually using the Travis versions of Python shown here, but useful to organize matrix
  # see: https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --set always_yes yes
  - conda update conda
install:
  - conda config --add channels conda-forge
  - conda create -q -n pyenv python=$TRAVIS_PYTHON_VERSION 
  - source activate pyenv
  - python -m pip install numpy scipy pytest pytest-cov pyyaml pycodestyle
  - conda install codecov
  - chmod +x ./
script:
  - pycodestyle lib.py
  - pytest --cov=lib
  - codecov
